### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by TheShadow29** [facebookresearch/grounded-video-description#6]
Thank you for the amazing repository. Could you share an estimate of how long the training process takes? Also, I noticed that during the training of a few batches, the gpu utilization is 0. Is there any particular reason for this? I haven't able to pinpoint the cause on my side.

**Comment by LuoweiZhou** [comment]
Hi @TheShadow29, single-GPU training from [here](https://github.com/facebookresearch/grounded-video-description#starter-code) takes about 30min per epoch and 20hr for 40 epochs on a TITAN Xp GPU. The original experiments are performed on 8x V100 GPUs at 16min per epoch. The low GPU utilization might result from data loading/caching since we save all feature files into individual files due to a legacy reason. If you want to further speed things up, you could consider binding all feature files into a giant or a few h5 files. Model-wise, consider distributed dataset parallel (see [here](https://pytorch.org/tutorials/intermediate/dist_tuto.html) and an example on [pytorch 0.4](https://github.com/salesforce/densecap/blob/master/scripts/train.py#L221)).

**Comment by TheShadow29** [comment]
@LuoweiZhou thank you for the pointers. There seems to some problem with running the code since its been around 9 hours and only 6 epochs are finished when using 4 gpus (4x 2080Ti)

I tried with just 1 gpu as well, but that too has gpu usage 0 except for a spike at irregular intervals. After 100 steps, it shows 
`step 100/1870 (epoch 0), lm_loss = 6.112, att2_loss = 0.000, ground_loss = 0.000,cls_los = 0.000, lr = 0.00050, time/batch = 298.568`

So that would imply ~5mins for 100 steps, or ~90mins for 1800 steps, appx 3x slower, which shouldn't really be the case. 

I followed the exact same steps you outlined, which includes creating the conda environment as well. I am also getting the correct evaluation scores by running the evaluation scores. 

Is there any possible reason that comes to mind?

**Comment by LuoweiZhou** [comment]
@TheShadow29 you might have slow data loading. Could you measure the time spent on data [loading](https://github.com/facebookresearch/grounded-video-description/blob/master/main.py#L202) and model forward/backward [pass](https://github.com/facebookresearch/grounded-video-description/blob/master/main.py#L226) (basically divide everything in [training](https://github.com/facebookresearch/grounded-video-description/blob/master/main.py#L201) into two parts)? The time spent on data loading should be negligible compared to the latter. Otherwise, you might have a slow shared file system (e.g., mounted NFS is bad at reading tons of small files, SSD could be much faster than HDD). Bind all feature files into one or a few [h5](https://github.com/ruotianluo/ImageCaptioning.pytorch/blob/master/scripts/convert_old.py#L18) files should help.

**Comment by TheShadow29** [comment]
You maybe onto something. Currently, I was using hdd (my mistake). I will try to load it from ssd and report back.

**Comment by TheShadow29** [comment]
@LuoweiZhou moving to SSD did the trick and the GPUs are no longer idle. Thank you for pointing me to that. 

I just have one last question, it seems that `iter(dataloader)` here https://github.com/facebookresearch/grounded-video-description/blob/master/main.py#L191 takes up some time to execute. Is there any specific reason for that?

**Comment by LuoweiZhou** [comment]
@TheShadow29 great to know that and we actively welcome pull requests if you have better solutions for the data loading. `iter` is basically to create an iterator object from the dataloader and might need some time for initialization.

**Comment by TheShadow29** [comment]
@LuoweiZhou Thank you for your time. Since the issue is resolved, I am closing it. Cheers!
